### PR TITLE
improving CI system

### LINKED ISSUE #52: Improve CI system
Needs:
* documentation build
* code coverage
* spack build
* build with different versions of w3emc
* Current workflows use develop branch of dependencies but cache them, caching should not be used with develop branch in CI.
* Test install.

### PR DESCRIPTION
**Pull request by edwardhartnett**
Fixes #52

### CODE REVIEW

**Comment by edwardhartnett** [comment]
I will add spack testing in a separate PR...

**Comment by Hang-Lei-NOAA** [comment]
This change seems only test on the tags of dependencies associated with certain version. Is it appropriate for new development?

**Comment by edwardhartnett** [comment]
@Hang-Lei-NOAA good question!

The developer workflow tests the develop version of everything.

The Linux_versions, Intel, and MacOS workflows test recently released versions of dependencies against the develop branch of this repo.

So we are testing both: 
1 - we continue to work with every dependency's develop branch
2 - we continue to work with the last (ideally) 3 releases of each dependency

**Review by Hang-Lei-NOAA — APPROVED** [review]
Okay

**Pull request merged**
